### ISSUE TITLE
[EPIC] - Open Source Ceph Dataset

### ISSUE THREAD

**Issue by chauhankaranraj** [aicoe-aiops/ceph_drive_failure#29]
As a data scientist working on disk health prediction for ceph,
I want access to disk health data from actual users’ ceph clusters,
So that I can train models using this data, which would likely result in more accurate and precise models than those created with external data.

As a Ceph product manager,
I want to anonymize and publish ceph telemetry data,
So that I can build an open source data science community around this data.

Totally open to ideas on how to approach this. One idea for an MVP is, we can manually extract and store one quarter of data (in a similar fashion as Backblaze) to an s3 bucket on the [operate-first](https://www.operate-first.cloud/) cluster. And have a small jupyter notebook that shows how to access this data, and also does some light EDA on it. Then if this seems like a suitable way to share data, we can go ahead and automate the data publishing process.

**Acceptance Criteria**
- [x] public s3 bucket on operate-first - https://github.com/aicoe-aiops/ceph_drive_failure/issues/32
- [x] add one quarter's worth of data to this bucket
- [x] data access + EDA notebook - https://github.com/aicoe-aiops/ceph_drive_failure/issues/33
- [x] publish on operate-first website

**Comment by chauhankaranraj** [comment]
Created #32 and #33 to split the tasks in this issue into smaller chunks.

**Comment by chauhankaranraj** [comment]
Data description, link, and EDA notebook published on operate first website [here](https://www.operate-first.cloud/data-science/ceph-drive-failure/docs/content.md#ceph-telemetry-dataset).
